version: '3.9'

services:
  api:
    container_name: flightwatch-api
    build: .
    environment:
      DATABASE_URL: $DATABASE_URL
      PORT: $PORT
      SKYSCANNER_API_KEY: $SKYSCANNER_API_KEY
      TWILIO_ACC_SID: $TWILIO_ACC_SID
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      TWILIO_PHONE_NUMBER: $TWILIO_PHONE_NUMBER
      CUTTLY_API_KEY: $CUTTLY_API_KEY	
    ports:
      - "8081:3000"
    depends_on:
      - db
  db:
    container_name: flightwatch-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "8082:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}

